// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIN-pQoCyvJuAIXs9OhuwyU-88xwsj2oM',
    appId: '1:613165082148:web:8f505e2bf9cf627c1a5ab1',
    messagingSenderId: '613165082148',
    projectId: 'grabage-8447d',
    authDomain: 'grabage-8447d.firebaseapp.com',
    databaseURL: 'https://grabage-8447d-default-rtdb.firebaseio.com',
    storageBucket: 'grabage-8447d.appspot.com',
    measurementId: 'G-M2Y1YB2R34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8srVoWQP0azcjk94tT8eiheLwcyo9sak',
    appId: '1:613165082148:android:295c95b93c9af7141a5ab1',
    messagingSenderId: '613165082148',
    projectId: 'grabage-8447d',
    databaseURL: 'https://grabage-8447d-default-rtdb.firebaseio.com',
    storageBucket: 'grabage-8447d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOwec7R0AqeQsxrcPonYho26eK0CaeNk',
    appId: '1:613165082148:ios:0786d4b3864c35801a5ab1',
    messagingSenderId: '613165082148',
    projectId: 'grabage-8447d',
    databaseURL: 'https://grabage-8447d-default-rtdb.firebaseio.com',
    storageBucket: 'grabage-8447d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoOwec7R0AqeQsxrcPonYho26eK0CaeNk',
    appId: '1:613165082148:ios:0786d4b3864c35801a5ab1',
    messagingSenderId: '613165082148',
    projectId: 'grabage-8447d',
    databaseURL: 'https://grabage-8447d-default-rtdb.firebaseio.com',
    storageBucket: 'grabage-8447d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIN-pQoCyvJuAIXs9OhuwyU-88xwsj2oM',
    appId: '1:613165082148:web:10d9a8ead52ec65c1a5ab1',
    messagingSenderId: '613165082148',
    projectId: 'grabage-8447d',
    authDomain: 'grabage-8447d.firebaseapp.com',
    databaseURL: 'https://grabage-8447d-default-rtdb.firebaseio.com',
    storageBucket: 'grabage-8447d.appspot.com',
    measurementId: 'G-ZJ9Y39CTCT',
  );

}