// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6HaIS0ZbZc-fCUC8Z_76j_qTUsCZQwQ',
    appId: '1:613252489615:web:f6e9451d411c2238fbebfa',
    messagingSenderId: '613252489615',
    projectId: 'fir-7a941',
    authDomain: 'fir-7a941.firebaseapp.com',
    storageBucket: 'fir-7a941.appspot.com',
    measurementId: 'G-5X9RM1Y5Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMZxQ4pDchcZhrLveTe2hGqofRRTEVxg',
    appId: '1:613252489615:android:33eb11190d8fc33dfbebfa',
    messagingSenderId: '613252489615',
    projectId: 'fir-7a941',
    storageBucket: 'fir-7a941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFdblmdholBBDICLZzQEiJBmUyZhR7-k',
    appId: '1:613252489615:ios:e4775a0b9281aed8fbebfa',
    messagingSenderId: '613252489615',
    projectId: 'fir-7a941',
    storageBucket: 'fir-7a941.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqFdblmdholBBDICLZzQEiJBmUyZhR7-k',
    appId: '1:613252489615:ios:895c705a9cfab74efbebfa',
    messagingSenderId: '613252489615',
    projectId: 'fir-7a941',
    storageBucket: 'fir-7a941.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
